permalink: pretty
markdown: kramdown

title: use NANO
author: Anthony Ramella
description: A directory of merchants accepting Nano cryptocurrency payments.

url: https://usenano.org
repo: https://github.com/tonyynot/usenano
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor

plugins:
  - jekyll-feed

gems:
  - jekyll-bootstrap-sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
